import React from 'react';
import type { Metadata } from 'next';
import { Urbanist, Open_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider, QueryProvider } from '@/context';
import { Toaster, Header } from '@/components';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const urbanist = Urbanist({ subsets: ['latin'] });
const open_sans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open_sans',
});

export const metadata: Metadata = {
  title: 'Resume builder.',
  description: 'Generated by create next app',
};

async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn('bg-background', open_sans.variable, urbanist.className)}>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <NextIntlClientProvider messages={messages}>
              <div className="h-auto min-h-screen w-full !bg-[#f8f8f8] dark:!bg-background">
                <Header />
                <div>{children}</div>
              </div>
            </NextIntlClientProvider>
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

export default MainLayout;
